
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int DIFERENCIA = 21;
  public static final int INTERSECCION = 19;
  public static final int FLECHA = 14;
  public static final int OPERA = 8;
  public static final int LISTA_ELEMENTOS = 6;
  public static final int ID = 2;
  public static final int DOS_PUNTOS = 17;
  public static final int PAREN_IZQ = 12;
  public static final int COMA = 15;
  public static final int PAREN_DER = 13;
  public static final int EOF = 0;
  public static final int INTERV = 3;
  public static final int CONJ = 7;
  public static final int UNION = 18;
  public static final int error = 1;
  public static final int COMPLEMENTO = 20;
  public static final int LISTA_CONJ = 5;
  public static final int LLAVE_IZQ = 10;
  public static final int EVALUAR = 9;
  public static final int LLAVE_DER = 11;
  public static final int LISTA = 4;
  public static final int PUNTO_Y_COMA = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INTERV",
  "LISTA",
  "LISTA_CONJ",
  "LISTA_ELEMENTOS",
  "CONJ",
  "OPERA",
  "EVALUAR",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "PAREN_IZQ",
  "PAREN_DER",
  "FLECHA",
  "COMA",
  "PUNTO_Y_COMA",
  "DOS_PUNTOS",
  "UNION",
  "INTERSECCION",
  "COMPLEMENTO",
  "DIFERENCIA"
  };
}

